callstack/haul

- docs/Configuration.md
This one had me puzzled. I followed the configuration docs to start customizing my project. I copy/pasted the last code example, changed the `rules` key to be an array (as webpack requires), and removed the custom bits in order to test:
```
module.exports = ({ platform }, defaults) => ({
entry: `./index.${platform}.js`,
module: {
...defaults.module,
rules: [
...defaults.rules
]
},
resolve: {
...defaults.resolve
}
});
```
I then received the following error:
Turns out the `...defaults.rules` spread should actually be `...defaults.module.rules`. Took me a while to figure that out :)
> Correct configuration docs

- bin/cli
- package.json
- src/cli.js
- yarn.lock
Fixing #63 as per this comment https://github.com/babel/babel-preset-env/issues/92#issuecomment-266869180
Babel-preset-env will use `regenerator-runtime` on Node 4, but we don't include polyfill from it. Turning on settings as in this PR will conditionally turn on polyfills as needed.
> Include polyfills with babel-preset-env

- src/loaders/assetLoader.js
Fixes an issue when running with --platform all makes assets overwrite each other (Android overwrites iOS and then, iOS keeps returning Android back icon for instance).
> Fix loader issues when running all platforms

- src/commands/start.js
- src/server/middleware/devToolsMiddleware.js
Fixes `debugger-ui` being opened on a wrong IP (typically `10.0.3.2` in Genymotion because of using `hostname`).
> Fix debugger issues on Android

- src/commands/init.js
Fixes #85
The process is:
1) If Haul is already in `package.json` scripts (any of scripts contains haul), we print info that it's already there and how to run it
2) If there's start script defined already and is not a default packager, we ask for a name for Haul script. By default it's start so users can opt-in to overwrite it
3) We use either start or name provided in point 2 to write package.json.
Questions:
1) Currently we add `haul start`. As of now, one has to pass `-- --platform [ios|android|all]` in order to start Haul for these platforms. Shall we print that as well?
> Add to package.json scripts

- src/commands/init.js
In this commit https://github.com/callstack-io/haul/pull/90/commits/afd93e1b42c050b9690d81419464e5ceb819ffb2 @grabbou changed the comparison from `>` to `===`.
I don't know if it was intended but it broke the script. If a section is matched and replaced it doesn't save but exits with an error.
> Fix iOS build phase

- src/commands/start.js
We forgot to define it after changing CLI interface. Results in `uglify` running for `npm start`.
> dev is true by default in `start`

- package.json
- src/server/index.js
- src/server/middleware/symbolicateMiddleware.js
- yarn.lock
This PR fixes #122 by removing the `body-parser` as suggested by @skellock and relying on `rawBodyMiddleware` for symbolication.
> Remove body-parser in favor of rawBodyMiddleware

- src/server/middleware/symbolicateMiddleware.js
If input source mappings are incomplete, stack frame lookups can fail and return nully values. I have observed this when trying to set up Haul to load TypeScript files. This causes the symbolicate endpoint to fail with JS's peculiar version of a NPE.
It would be better to return the original stack frame for mappings that cannot be resolved. Then at least the mappings that *were* resolved can be seen. The underlying cause of the incomplete mappings is kind of beside the point. Better some than none, right?
This PR turns this:
into this:
Which, perhaps you'll agree, is a distinct improvement. Plus no nasty error messages in the webpack log.
> Fail gracefully on source mapping lookup

- package.json
`npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli.`
babel doesn't seems to be used, so we can remove it to remove the warning when installing haul.
> remove babel

- package.json
needed by `babel-register` so should be in `dependencies`
> fix misplaced babel plugin

- docs/CLI Commands.md
- src/commands/bundle.js
- src/commands/start.js
- src/messages/webpackConfigNotFound.js
- src/utils/getWebpackConfig.js
Allow to specify the path to the config file as an option
`haul start --config ./path/to/config.js`
> add config path as an option

- README.md
The badge link was missing http and was linking to a relative path
> Fixes slack badge link

- package.json
- src/messages/editorNotConfigured.js
- src/messages/index.js
- src/server/index.js
- src/server/middleware/openInEditorMiddleware.js
- src/server/middleware/symbolicateMiddleware.js
- src/types.js
- yarn.lock
This PR adds support for tapping on a stack trace in the simulator.  It will open the user's editor to the right line/column.
There's a few ways to use it, here's the easiest:
```sh
export REACT_EDITOR=code
```
This works too:
```sh
export REACT_EDITOR=/usr/local/bin/code
```
[The library we're using](https://github.com/lahmatiy/open-in-editor) supports about a dozen editors and it knows where to look for the standard installs.  It knows how to launch them and use the right order for parameters.
For custom installs, we had to invent some things:
```sh
export HAUL_EDITOR=sublime
export HAUL_EDITOR_CMD="/path/to/Sublime Super Mega Beta.app"
export HAUL_EDITOR_PATTERN="-r -g {filename}:{line}:{column}"
```
That's for more advanced setups.
Out of the box, if no environment variables are …
> Opens an editor when tapping a stack frame.

- src/utils/polyfillEnvironment.js
This is actually running in the browser and throwing an error that can make script injection fail
> check for global.self first

- README.md
- package.json
- src/commands/init.js
Now that I have access to `haul` on npm, we can switch to it.
> Use new name

- src/utils/findProvidesModule.js
- src/utils/resolveModule.js
1. `react-native init testApp`
2. `cd testApp && yarn add haul`
3. `yarn run haul -- --platform ios`
4. `react-native run-ios` (in other tab)
5. Stop `haul` by Ctrl+C and run again: `yarn run haul -- --platform ios`
```
ERROR  Error running yarn run haul -- --platform ios
Error: ENOENT: no such file or directory, stat '/Users/paweltrysla/Documents/TrueCar/testRNApp/node_modules/react-native/third-party/glog-0.3.4/test-driver'
at Object.fs.statSync (fs.js:968:11)
at walk (/Users/paweltrysla/Documents/TrueCar/testRNApp/node_modules/haul/src/utils/findProvidesModule.js:60:21)
at fs.readdirSync.forEach.file (/Users/paweltrysla/Documents/TrueCar/testRNApp/node_modules/haul/src/utils/findProvidesModule.js:67:9)
at Array.forEach (native)
at walk …
```
> Fix findProvidesModule throwing error in while running start command

- src/utils/resolveModule.js
Fixed a bug where we did not remove `package.json` from directories' path.
Fixes #170 and #175
> HasteResolver not resolving on Windows

- src/utils/haul-integrate.sh
haul build failed in the latest RN version.
`react-native/packager` folder is no longer exist in RN 0.46, check if the folder is exist or not. if not use `react-native/script` folder
More information: 
https://github.com/facebook/react-native/issues/14935#issuecomment-314160539
> test react-native/packager is exist or not, if not use react-native/script

- src/loaders/assetLoader.js
Fixes https://github.com/callstack-io/haul/issues/180
> Fix assetLoader not using platform path separator

- package.json
Happypack as a git module seems to have random issues on some machines. Since there is a published version that appears to work fine, I added that as a dependency instead.
> Updated happypack version, closes #190

- src/server/assets/debuggerWorker.js
- src/server/middleware/symbolicateMiddleware.js
Before:
After:
Errors are visible now, but stack trace is pointing back to `worker`.
Still WIP.
> Better Error messages

- src/utils/polyfillEnvironment.js
Turns out in Webpack environment, it's always a module. Fixes #188
> Fix console log

- package.json
- yarn.lock
This PR addresses #204. The problem was in a react-native preset, where regenerator-runtime was undefined.
Big props to @zamotany for nailing down the problem 👍
> Update react-native preset

- src/messages/index.js
- src/messages/webpackCompilerPlatformNotFound.js
- src/server/middleware/symbolicateMiddleware.js
- src/utils/getCompilerByPlatform.js
A fix for #176 which revealed that symbolication didn't work while in `--platform all` mode.
So, I had thought that React Native passed the platform when did it's symbolicate request.  It doesn't.  😿 
What I'm doing now is "detecting" it by looking at the first frame's unresolved filename.  Somewhere in there it'll say `...index.ios.bundle?platform=ios&...`.  I'm matching the platform found there against the webpack `options.output.filename` config.  
Not award-winning, but it works.  Would be nicer if there was a easier way to get the platform from the config.  I created a helper `getCompilerByPlatform` where we can put that.
Something presumptuous I snuck in (I know @grabbou & @satya164 will rightfully call me out on this) is, if we can't find the platform (due to an error in the …
> Adds error symbolication in multi-platform mode.

- src/utils/haul-integrate.sh
When packager is being launched by Xcode during run phase (by `launchPackager.command`), current working directory is set to `/`. This results in an awkward error saying "Cannot find /node_modules/.bin/haul" (note it looks in wrong folder - in this case, top level one).
In order for this to function properly, we need to use $THIS_DIR variable that is set by `launchPackager.command` before executing `packager.sh` script.
> Fix `launchPackager` step from Xcode

- src/server/index.js
I failed at reading the webpack-dev-server code. It exposes a parameter for adding mime-type detection. This ensures that the `.bundle` file is served with an `application/javascript` content-type.
https://github.com/callstack-io/haul/pull/229 is unnecessary, but things are still broken pending fix of https://github.com/facebook/react-native/issues/15791
> Set mimetype for bundle files

- src/server/middleware/symbolicateMiddleware.js
At the moment, `symbolicateMiddleware` expects [`getRequestedFrames`](https://github.com/callstack/haul/blob/master/src/server/middleware/symbolicateMiddleware.js#L73) to return `null` if something was wrong with the stack or a non-empty array of frames if all goes well. 
This leads to an error edge case where the code blows up if `getRequestedFrames` returns an empty array.
```
TypeError: Cannot read property 'file' of undefined
at symbolicateMiddleware (MY_PATH/node_modules/haul/src/server/middleware/symbolicateMiddleware.js:124:27)
...
```
Because [this line](https://github.com/callstack/haul/blob/master/src/server/middleware/symbolicateMiddleware.js#L124) assumes it will operate on a non-empty array:
```js
const platformMatch = unconvertedFrames[0].file.match(/* ... */)
// …
```
> Improve symbolicateMiddleware stackframe existence checks.

- src/server/index.js
This will allow the remote debugger to make requests to the dev server when browser's remote debugger address and dev server address differ.
> Set CORS header for remote debugging

- src/cliEntry.js
- src/commands/start.js
- src/utils/haulPortHandler.js
This feature gives user a choice what to do when server port (default) 8081 is already in use. We can kill the process that uses the port and proceed with startup or simply quit.
Fix for #207
> Handle situation when server port is in use

- src/utils/haul-integrate.sh
In the latest beta of haul we get the following error when the packager is started:
```
/Users/unixusername/Documents/project/projectname/node_modules/react-native/scripts/packager.sh: line 1: cd: ../node_modules/haul/src/utils/../../../: No such file or directory
```
To fix this `THIS_DIR` in `haul-packager.sh` should return an absolute path instead of relative path since the packager is started in a new shell.
Versions: 
OS: Mac OSX Sierra
haul v1.0.0-beta.6
react-native: 0.47.1
react: 16.0.0-alpha.12
> THIS_DIR in haul-integrate.sh returns relative path instead of absolute

- package.json
- src/hot/client/importScriptsPolyfill.js
- src/messages/bundleBuilt.js
- yarn.lock
I've just released a major bump of the `eslint-config-callstack-io`, so here it is.
> chore: bump eslint callstack config

- src/server/assets/debugger.html
This PR use quotation mark `"` to wrap HTML param value against apostrophe `'` in `src/server/assets/debugger.html`
> Use quotation marks for HTML param values

- src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
- src/utils/makeReactNativeConfig.js
#115 
Bundle size went down from 1MB+ to 621KB (65KB behind metro-bundler) for fresh RN project.
We should see more size decrease if we stop transpiling ES imports/exports to CJS.
> Use module concatenation plugin and set NODE_ENV to production

- src/messages/bundleBuilt.js
> Fix build time display

- src/server/assets/debuggerWorker.js
- yarn.lock
I've recently (#278) run into troubles with Haul and [Lottie](https://github.com/airbnb/lottie-react-native).
The problem is that Lottie relies upon [react-native-safe-module](https://github.com/lelandrichardson/react-native-safe-module) and there is the issue. React-native-safe-module is trying to ["patch" the native module in order to prevent crashes](https://github.com/lelandrichardson/react-native-safe-module/blob/master/src/NativeSafeComponent.js#L109) but the author doesn't count on that [requireNativeComponent() could return a string](https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/requireNativeComponent.js#L57) and that's the issue – when you try to modify `string primitive` property under strict mode in web worker environment you get the `Cannot create …
> Set proper environment for remote debugging

- src/hot/client/index.js
`makeHot` should behave correctly and should return original `rootFactory` not `undefined` otherwise the apps in production mode will get broken. 🙏
> fix(hmr): makeHot in production mode

- src/hot/client/hotPatch.js
HMR would thrown an error when it finds registered function that is on a prototype. With this patch, we just make sanity check if function is on `Object.prototype`, if so, it's not a component.
> HMR hotfix

- fixtures/react-native-with-haul/package.json
This way you can easily type `yarn haul <command>` and test it. In time, it would be nice to extend this fixture/example to use some native code for example and test how we do with upgrading to next RN version with `react-native-git-upgrade`.
For manual testing purposes we can leave old fixtures, just so we're able to easily test different RN versions.
> Use local haul binary in fixture

- fixtures/react-native-clean/package.json
- src/commands/init.js
This was bothering me since very beginning of using Haul. With `yarn` it's even unnecessary to add this, but I'm not sure if `npm` is as smart.
With `"haul": "haul"` instead of `"haul": "haul start"` inside npm-scripts, you can now invoke any haul command, not just start with some arbitrary args:
```sh
yarn haul # $ haul start
```
```sh
yarn haul start # $ haul start
```
```sh
yarn haul build --platform ios # $ haul build --platform ios
```
And so on. Also `start` is the default command, so 2 points for me.
> Change "haul start" to "haul" as a default npm-script

- package.json
- yarn.lock
Sice Webpack 3.9.0 they introduce some changes that self is used before this as global.
This is just a walkaround for issues related to #308 *Can't find variable: self* . I need to dig more into it.
Background: https://github.com/webpack/webpack/pull/5862
P.S: Maybe we can force all the version to avoid such a bug in future? What do you think?
> fix(webpack): Stick with Webpack 3.8.x

- src/commands/start.js
We should keep it simple and run `adb` from a path. Assumes that user has environment setup correctly according to https://facebook.github.io/react-native/docs/getting-started.html
Fixes #331
> Run adb command from path at first

- .gitignore
- README.md
- src/server/middleware/requestChangeMiddleware.js
There is a new experimental feature by Metro, called Delta bundles. It's turned on by default, and currently we have no proper implementation of it yet. Need to further investigate.
Added appropriate `Limitation` entry, how to disable that feature.
> Fix React Native 0.52+

- .npmignore
We shouldn't release fixtures to end users.
> Add fixtures to .npmignore

- src/utils/polyfillEnvironment.js
For production build regexp not matched anything and `scriptURL.match(/(^.+)\/index/)[1]` throws error because match was `null`, so i added statement for checking match and return null if not matched.
Fixes #349
> Fix scriptUrl for production build

- src/utils/polyfillEnvironment.js
We have a project where we have more entry-points in addition to the `index.js`, but these other entry-point files don't have `index` in their name.  (If you're curious about the  use-case for this, it's because we are using [react-native-threads](https://github.com/joltup/react-native-threads).
This PR is a different strategy for finding the dev server origin without looking specifically for `index`.  I'm very open to feedback on this approach or if anyone has a better idea for going about it.
> support bundle files without "index" in the name

- package.json
- src/hot/client/utils.js
- src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
- src/utils/__tests__/makeReactNativeConfig.test.js
- src/utils/makeReactNativeConfig.js
- yarn.lock
@czystyl can you make me a favor and test it once more? I've updated webpack to stable v4.1.0
> Upgrade to Webpack 4

- src/utils/resolveModule.js
Haste does not play nice with symlinks, and when react-native is symlinked, react native fails to resolve modules that aren't imported via relative paths. This resolves the sym link issue by resolving a real path for react-native, letting Haste do its thing.
As far as I can tell, this resolveModule.js is only referenced when building the react native webpack config, and is only used for react-native. Please let me know if there is a better place to put this.
> Fixing Haste module resolution when react-native is symlinked

- src/utils/polyfillEnvironment.js
Hi,
This is part of a greater change to get tree shaking to work with react-native. In order to use webpack's tree shaking I need to remove the use of haste. I'm planning to start a discussion upstream in react-native but I also wanted to make the haste references that haul uses in polyfillEnvironment.
I'm planning to use this fork to show how someone could use haul and webpack with react-native to get tree shaking to work on their react-native apps. In my example on an android test project is was able to shrink the bundle size from 500k with metro to 260k using haul.
I'm also open to writing a babel-plugin to de-haste the source but I thought I would try to make these small changes in haul.
> remove haste references from polyfillEnvironment

- src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
- src/utils/makeReactNativeConfig.js
Since React Native 0.54 `metro/src/lib/bundle-modules/MetroClient.js` file is being included into bundle, and it contains a not traspiled `const` which makes Android sad.
> Explicitly transpile `metro` dependency (fixes #400)

- src/utils/haul-integrate.sh
Remove escape characters around $@ to allow additional parameters to be used within the haul integrate script
> fix: remove escape characters around $@

- src/utils/getConfig.js
It's nice to inform a user that Haul is trying to run in "default" mode. It could help to avoid confusion in case that user misspells the config file.
Feel free to rephrase it.
> Inform user that compiler uses ZERO-CONFIGURATION 🚀mode

- src/commands/bundle.js
- src/commands/start.js
- src/constants.js
- src/messages/webpackConfigNotFound.js
- src/utils/getConfig.js
- src/utils/getWebpackConfigPath.js
I think it's a good idea to search for `webpack.haul.js` which is deprecated config name in favor of `haul.config.js`.
If no config is specified by `--config` Haul will try to find `haul.config.js` first, then it tries to find `webpack.haul.js` if no of them is found he will run in zero-configuration™ mode.
If a user specifies `--config` and that path is non-valid, Haul will throw an error says that.
@satya164 if you are reading this, feel free to rephrase the comments. 💪
> Seek for the deprecated config file 🔎

- src/utils/makeReactNativeConfig.js
This resolves #417.
Since any plugin in a full webpack config _could_ affect module resolution, this change removes the Haul-specific entrypoint verification.
> Remove webpack entry verification checks

- src/compiler/Compiler.js
- src/compiler/Fork.js
- src/compiler/createWebSocketServer.js
I've discovered that we are using ws@2.2.0 which has the deflate option turned *on* by default. This issue is not actually about deflate but about `maxPayload`. (maxPayload error blown the zlib).
This is supposed to be just a walk around because I'm still not sure how the size is computed thought.
- My test project should be 42 633 230 byte. _(this is in Haul's logs or when I dowload the bundle into file via `wget -O bundle http://localhost:8081/index.ios.bundle` or something)_
- Default `maxPayload` ws@2.2.0 is 104 857 600 byte. (https://github.com/websockets/ws/blob/2.2.0/lib/WebSocketServer.js#L46)
- However, the `ws` claim that the bundle file is 144 242 145 byte (I had loged this in the context of very ws itself: https://github.com/websockets/ws/blob/2.2.0/lib/Receiver.js#L467).
I …
> Don't use deflate & better socket error handle 

- src/commands/start.js
`adb reverse` is only run when `platform` is `android`, it should be run if `platform` is `all` also.
> Run adb reverse when platform is 'all'

- docs/Recipes.md
- src/cliEntry.js
- src/commands/bundle.js
- src/compiler/Fork.js
- src/resolvers/HasteResolver.js
- src/server/middleware/devToolsMiddleware.js
- src/server/ui.js
- src/server/util/getRequestDataFromPath.js
- src/types.js
- src/utils/findProvidesModule.js
- src/utils/getConfig.js
- src/utils/getHaulConfig.js
- src/utils/makeReactNativeConfig.js
This expands the config returned in haul.config.js to allow it to specify additional platforms, and expands the options used in createWebpackConfig to allow additional packages and platform extensions to be included in the haste map.
See #418
> allow out-of-tree platforms to be dynamically added

- docs/Configuration.md
- docs/Recipes.md
Hello there!
Looks like there's a new configuration style for haul and unfortunately `Recipes.md` with TypeScript setup was forgotten. The old one still works but it's showing deprecation warning. I had a moment to play with it a bit more and eventually I got it to work. Doing this PR, in case anyone alse might find it useful.
> Updating TypeScript configuration to the new style in Recipes

- integration_tests/__tests__/__snapshots__/init.test.js.snap
- integration_tests/__tests__/init.test.js
- src/commands/init.js
- src/messages/generatedConfig.js
Fixes #441.
Updates init command to output haul.config.js instead of webpack.haul.js, as well as referencing src/constants.js for easier future updates.
> update `haul init` output to match new spec (#441)

- src/commands/reload.js
The default `8081` port was hardcoded.
> Add --port option to `haul reload` command

- src/utils/__tests__/__snapshots__/getBabelConfig.test.js.snap
- src/utils/getBabelConfig.js
When running `haul` within a monorepo, the default behavior is to compile everything which is not in `node_modules` (with a few [exceptions](https://github.com/callstack/haul/blob/master/src/utils/makeReactNativeConfig.js#L78)). Webpack will use the realpath rather than the symlink path when processing rule `excludes`. As a result, any sibling packages within a monorepo gets compiled (this is desired behavior in my case).
Where the issue arrises, is that babel looks to resolve presets/plugins relative to the [file being transformed](https://github.com/babel/babel/issues/2974#issuecomment-155738271). It doesn't make sense for packages agnostic of distribution (web, native, etc...) to have to define `babel-preset-react-native` as a dependency. This should only be required within the …
> Resolve path to `react-native` preset

- yarn.lock
Follow-up from #454. This resolves the following error on Node 10:
```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
```
> Upgrade upath in lockfile

- package.json
- src/utils/__tests__/__snapshots__/getConfig.test.js.snap
- src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
- src/utils/makeReactNativeConfig.js
- yarn.lock
The default `minimizer` created by Webpack does not provide a `test` options, so the default tests just for `.js` files. Since we rely on a different extension for our output bundles, we need to explicitly use `UglifyJsPlugin` ourselves.
Fixes #458
> Fix minimization of bundles

- src/commands/init.js
Fixes #376 
Instead adding a `project.ext.react` initialization with the `cliPath` for haul which could potentially clobber existing config, this initializes the `project.ext.react` config map if necessary, and then explicitly assigns the `cliPath` value.
> gracefully add gradle cliPath config

- package.json
- yarn.lock
Lock `react-slate` dependencies before releasing new version - `0.8.0`, which might have cause issues without migrating the UI code in Haul.
The follow-up PR will update those dependencies and migrate Haul + add `ScrollView`.
> chore: lock react-slate dependencies

- .gitattributes
All the lint rules blow up if you use CRLF, making working with the repo on windows very annoying.
This forces windows machines to keep the js files with LF when cloning the repo.
> Force js files to use LF even on windows

- .gitattributes
- integration_tests/__tests__/bundle/bundle.android.test.js
- integration_tests/__tests__/bundle/bundle.ios.test.js
- integration_tests/__tests__/init.test.js
- integration_tests/__tests__/start.test.js
- integration_tests/runHaul.js
- integration_tests/utils.js
- jest/helpers.js
- src/compiler/worker/runWebpackCompiler.js
- src/utils/__tests__/getEntryFiles.test.js
This makes a couple of minor modifications to allow the tests and snapshots to work on windows.
- Use `yarn.cmd` instead of `yarn` when using spawn on windows.
- Use `node haul/cli.js` instead of just `haul.cli.js` to run haul
- Use some additional substitutions when outputting the snapshot files, so that windows machines get the same result (Mostly logic around the root directory format, and of course the directory separators.
> Modify tests to work on windows

- docs/HMR_react-navigation.md
- src/hot/client/hotApi.js
This will fix the `makeHot` so it doesn't force-rerender every tiny little change that happens when used with routers.  It does this by not building a brand new component on every call of the resulting function. 
```javascript
const HotView = makeHot(() => HomeView, 'Home');
console.log(HotView() === HotView());
```
> Before the above would return false, therefore a re-render would be forced every time . `getScreen` is called by `react-navigation`
Note that this will still cause problems when utilized as documented since
```javascript
console.log(makeHot(() => HomeView, 'Home')() !== makeHot(() => HomeView, 'Home')())
```
Solution there would likely to use a `Map` of some sort to identify when we should return the previously created component instead of creating a new one.  Since I …
> fix makeHot

- src/utils/__tests__/__snapshots__/getConfig.test.js.snap
- src/utils/makeReactNativeConfig.js
Per @thymikee comment in https://github.com/callstack/haul/issues/502#issuecomment-443130976 - I added @react-navigation to the regex pattern and updated snapshots.  
I had to modify my webpack config when I updated a couple weeks ago, so this is a nice addition.
> Fix: add @react-navigation to regex to include in transform

- src/utils/makeReactNativeConfig.js
Previously it was asking users to stop using the deprecated style of configuration while still pointing to docs for the deprecated style of configuration.
Might want to make a note to change this link back to `master` once `next` is merged into it.
> Update link to docs to point to the new docs

- src/utils/__tests__/__snapshots__/getBabelConfig.test.js.snap
- src/utils/getBabelConfig.js
This PR enables webpack's tree shaking by not allowing babel to transform `import`/`export` statements to commonjs modules.
https://webpack.js.org/guides/tree-shaking/
**More info**
We noticed we were getting bigger bundles when using metro vs haul. We use webpack and tree shaking for our web bundles which greatly reduces their size.
Since haul uses webpack and webpack takes care of the `import` and `export` statements I think it would make sense to let webpack take care of this and do it's magic?
We enabled this same setting on our mobile bundle by using the custom `.babelrc` option and saw a significant reduction in size of 366 KB from 2.17 MB to 1.80 MB.
There might be a reason why you haven't done this already, but I couldn't find any info around it in the current issues. I worked …
> Do not transpile to commonjs to enable webpack tree shaking

- src/commands/start.js
temp directory for assetDest was wrongly being created in project root, instead of `tmp`.
Fix for #519
> Fixing temp directory path for assetDest

- src/utils/__tests__/__snapshots__/getConfig.test.js.snap
- src/utils/makeReactNativeConfig.js
The new @react-native-community slider & asyncstorage libs for RN59 are shipped with flow types and require transpilation. This PR makes sure that all those libs are transpiled by default. This should typically not lead to any performance issues, as this code is almost always a small javascript interface to the native code. More of these libs will become available as part of the react-native lean code initiative.
This solves these issues:
```
ERROR  Failed to compile.
./node_modules/@react-native-community/slider/js/Slider.js 17:12
Module parse failed: Unexpected token (17:12)
You may need an appropriate loader to handle this file type.
| const RCTSliderNativeComponent = require('./RNCSliderNativeComponent');
|
> import type {NativeComponent} from …
```
> Add transpilation of @react-native-community

- src/commands/bundle.js
Xcode seems to fail if the verbosity level is set to anything other than `verbose`. Some of the characters used in the other levels makes Xcode think that errors have occurred. This was filed as #514 but was closed a bit early since there is a workaround.
The patch detects whether we're in interactive mode and applies the correct verbosity level.
By default, without adding `--progress verbose` to the bundle command, Xcode should not fail.
> Avoid tripping Xcode's script error detection.

- src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
- src/utils/__tests__/makeReactNativeConfig.test.js
- src/utils/makeReactNativeConfig.js
`namedModules` tells webpack to use readable module identifiers for better debugging.
See https://webpack.js.org/configuration/optimization/#optimizationnamedmodules.
We should disable it in production mode to reduce the bundle size.
The output bundle should work as before.
> Disable namedModules in prod to reduce bundle size.

- src/loaders/assetLoader.js
When the asset loader evaluates the sizes of a new asset, it will also log the path to the asset. Whenever the logger outputs a new log line during a Webpack build, Webpack will repeat the following log line: `Webpack: Starting ...`. This PR adds makes the logging of the asset path conditional on the `--verbose` flag, similar to other log events in the same file.
Before:
```
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
Webpack: Starting ...
√ Compile modules
> Build modules (96%)
→ 1271 of 1322 modules :: [path]
```
After
```
Webpack: Starting ...
√ Compile modules
√ Compile modules
√ Build modules
√ Optimize modules …
```
> Mark asset path logs conditional on --verbose

- packages/haul-core/src/constants.ts
When trying to bundle I'm getting the error:
ModuleNotFoundError: Module not found: Error: Can't resolve '<path>/node_modules/@haul-bundler/core/build/loaders/assetLoader' in '<path>'
the right path is  '<path>/node_modules/@haul-bundler/core/build/webpack/loaders/assetLoader'
> Update assertLoader correct path

- fixtures/exampleApp_0_59x/.gitignore
- fixtures/exampleApp_0_59x/haul.config.js
- packages/haul-core/src/config/types.ts
- packages/haul-ram-bundle-webpack-plugin/README.md
- packages/haul-ram-bundle-webpack-plugin/src/WebpackRamBundlePlugin.ts
Support asset regex in RAMBundle config:
`haul.config.js`:
```js
{
ramBundle: {
assetRegex: {
ios: /assets\//,
otherPlatform: /regex\//
}
}
}
```
> [FEAT] support asset regex

- packages/haul-core-legacy/src/compiler/worker/runWebpackCompiler.js
`watchOptions` is not correctly forwarded to webpack's watcher.
It is currently not possible to set [`watchOptions`](https://webpack.js.org/configuration/watch/#watchoptions). With this fix, it will be correctly forwarded.
Add the following lines (or similar) to `haul.config.js`:
```js
watchOptions: {
ignored: /.*\.tsx?$/
}
```
When you touch a `.ts`/`.tsx` file, Haul shouldn't recompile.
> fix: forward watchOptions to fs watcher.

- packages/haul-babel-preset-react-native/package.json
- packages/haul-babel-preset-react-native/src/index.ts
- yarn.lock
Native async/await behave incorrectly on RN 0.59 on both platforms and they not always resolve or resolve under certain conditions.
> fix: transpile async/await in `haul-bundler/babel-preset-react-native`

- packages/haul-core/src/server/setupDevtoolRoutes.ts
React Native is sending a methodName in the payload that fails validation.
To reproduce, throw an exception somewhere in your React Native app. From the error screen, tap in one of the stack frames. Haul's log before this would show `POST /open-stack-frame 400` and do nothing.
After this change, it should open your editor in the file referenced in the stack frame.
> Fix /open-stack-frame validation

- packages/haul-babel-preset-react-native/src/index.ts
`hermes` option was read from the wrong parameter. This is now fixed.
All existing tests should still pass.
> fix: hermes option read from wrong param

- docs/Configuration.md
This commit updates the Configuration doc to include a note about
configuring the server to use host '0.0.0.0' if there is an issue
connecting to the dev server on localhost.
I experienced an issue where my react native app running on a ios device
could not connect to the development server when using the default
(localhost) server configuration. Changing the host to 0.0.0.0 fixed the
issue for me so others might find that advice useful as well.
This pull request just adds a note to the docs that might help people solve issues connecting to the dev server from a device. 
n/a: docs only change
> docs: add note about localhost/0.0.0.0 issue

- fixtures/react_native_with_haul_0_60x_ts/haul.config.js
- integration_tests/react_native_0_60x_ts/__tests__/start.test.ts
- integration_tests/utils/server.ts
- packages/haul-cli/src/commands/start.ts
> fix: port setting in haul.config.js not used

- packages/haul-ram-bundle-webpack-plugin/src/IndexRamBundle.ts
Currently when generating source maps, we stringiyf the in-progress
indexMap once for every. single. file. even though we only care about
the final result (and indeed overwrite our previous stringification each
file). This was likely a typo and intended to be outside the forEach, so
this change moves the stringification to after we're fully done building
up the indexMap. This dramatically speeds up source map generation since
we're doing significantly less work with fewer allocations and GCs.
> fix: Speed up source map generation by only stringiying at the end

- packages/haul-core/src/utils/runAdbReverse.ts
The ANDROID_HOME environment variable defines where to find platform tools like adb, and occasionally (my setup), these aren't in the global system PATH. This explicitly uses the path to access adb instead of relying on it being in the system PATH.
No tests needed AFAIK - unless there is coverage here that I don't know about.
> Reads ANDROID_HOME for adb location

- packages/haul-core/src/preset/__tests__/__snapshots__/makeConfigFactory.test.ts.snap
- packages/haul-core/src/preset/utils/getSourceMapPlugin.ts
- Generate inline source maps for `.ts`/`.tsx` files.
- Split source with inline source maps and without into separate groups - `webpack://` and `webpack-internal://` for better visibility of sources with maps
> fix: inline source maps for TS + split source w/ and w/o maps

- packages/haul-core/package.json
- packages/haul-core/src/runtime/Logger.ts
- packages/haul-core/src/server/InteractiveUI.ts
- packages/haul-core/src/server/NonInteractiveUI.ts
- packages/haul-core/src/server/Server.ts
- yarn.lock
- requests will be now logged with standard format like other logs eg: `info ▶︎ GET /index.bundle`
- logs will be wrapped using https://github.com/chalk/wrap-ansi and will take all available width
- requests will be now logged to a file as well if `--output-file` is passed
> feat: improved logging and server UI

- packages/haul-babel-preset-react-native/src/index.ts
Conditionally add `@babel/plugin-transform-react-jsx-source` so we don't get `__source` injected into production bundles, and reduce the bundle size.
All current tests should pass.
> fix: only add plugin-transform-react-jsx-source in dev

- packages/haul-core/assets/debuggerWorker.js
- packages/haul-core/src/server/setupDevtoolRoutes.ts
This enables support for supplying the packager host by using
debug_http_host on Android or by changing bundleURL in
RCTWebSocketExecutor.m on iOS.
It is now possible to run an application on more than Device/Emulator, as one is not dependent anymore on `adb reverse` (on Android), when the host machine's IP address is used.
The supplied host (for example the host's machine IP address) is then used to open the debugger on the correct URL (instead of the previous hardcoded `localhost`).
1. Edit `haul.config.js` in the `react_native_with_haul` and add a server config with a custom host and port.
2. 
- For Android: Add the following in `MainApplication.java:onCreate`
```java
PreferenceManager.getDefaultSharedPreferences(getApplicationContext()).edit()
.putString("debug_http_host", …
```
> feat: Use supplied packager host

- packages/haul-core-legacy/package.json
- packages/haul-core-legacy/src/compiler/Compiler.js
- packages/haul-core-legacy/src/compiler/Fork.js
- packages/haul-core-legacy/src/compiler/createWebSocketServer.js
- packages/haul-core-legacy/src/compiler/worker/initWorker.js
> fix: crash when initialising compiler and forks

- e2e/utils/runHaul.ts
- fixtures/react_native_windows_e2e_app/babel.config.js
- packages/haul-babel-preset-react-native/src/index.ts
- packages/haul-ram-bundle-webpack-plugin/src/__tests__/integration.test.ts
> fix: include CJS transform when testing in Babel preset

- packages/haul-babel-preset-react-native/src/index.ts
Hermes doesn't support spread operator. Added the necessary plugins to transform them to ES5 syntax.
All tests should pass.
> fix: transform spread operator for Hermes

- docs/Configuration.md
- docs/Recipes.md
- fixtures/react_native_windows_e2e_app/__tests__/appium.test.js
- fixtures/react_native_windows_e2e_app/haul.config.js
- fixtures/react_native_windows_e2e_app/src/ExchangeRates.js
- fixtures/react_native_windows_e2e_app/src/Films.js
- fixtures/react_native_windows_e2e_app/src/app1.js
- fixtures/react_native_windows_e2e_app/src/host.js
- fixtures/react_native_with_haul_0_59x/haul.config.js
- packages/haul-cli/src/commands/bundle.ts
- packages/haul-cli/src/commands/ramBundle.ts
- packages/haul-core/src/preset/withPolyfillsFactory.ts
> feat: use webpack to resolve initializeCoreLocation file

- packages/haul-babel-preset-react-native/src/index.ts
Depending on your setup and usage (e.g. macOS vs Windows, bundle vs. dev server), Hermes won't be able to execute your bundle without these additional plugins.
All current tests should pass.
> fix: additional plugins for Hermes

- packages/haul-core/assets/debuggerWorker.js
> fix: assign location.host only if self is available in debuggerWorker.js

- docs/Configuration.md
- docs/Recipes.md
- packages/haul-core/package.json
- packages/haul-core/src/config/types.ts
- packages/haul-core/src/preset/__tests__/__snapshots__/makeConfigFactory.test.ts.snap
- packages/haul-core/src/preset/__tests__/makeConfigFactory.test.ts
- packages/haul-core/src/preset/makeConfigFactory.ts
- packages/haul-core/src/webpack/plugins/LooseModeWebpackPlugin.ts
- packages/haul-core/src/webpack/plugins/__tests__/LooseModeWebpackPlugin.test.ts
- packages/haul-core/src/webpack/plugins/__tests__/__fixtures__/index.js
> feat: add LooseModeWebpackPlugin and looseMode config plugin

- README.md
- e2e/react_native_0_60x/__tests__/explore-bundle.test.ts
- e2e/react_native_0_60x/__tests__/explore-ram-bundle.test.ts
- e2e/utils/bundle.ts
- e2e/utils/runProcess.ts
- packages/haul-explore/README.md
- packages/haul-explore/bin/haul-explore.js
- packages/haul-explore/package.json
- packages/haul-explore/src/index.ts
- packages/haul-explore/src/ram-bundle/computeFileSizes.ts
- packages/haul-explore/src/ram-bundle/index.ts
- packages/haul-explore/tsconfig.json
- packages/haul-explore/typings/metro/index.d.ts
- packages/haul-ram-bundle-webpack-plugin/src/FileRamBundle.ts
- packages/haul-ram-bundle-webpack-plugin/src/IndexRamBundle.ts
- yarn.lock
This PR add @haul-bundler/explore package which is a wrapper for [danvk/source-map-explorer](https://github.com/danvk/source-map-explorer)
[PR for source-map-explorer](https://github.com/danvk/source-map-explorer/pull/157)
> Source map explorer

- packages/haul-preset-0.60/src/defaultConfig.ts
Fixes https://github.com/callstack/haul/issues/701
> fix: prevent async imports from creating chunks

- package.json
On Windows, initial clone+yarn will end up with:
```
yarn install v1.17.3
[1/4] Resolving packages...
success Already up-to-date.
$ yarn clean && yarn build:source && yarn build:ts
yarn run v1.17.3
$ rm -rf ./packages/*/build ./packages/*/tsconfig.tsbuildinfo
'rm' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```
This PR uses `rimraf` package to perform clean script in a cross-platform way.
> fix: use rimraf for clean script

- packages/haul-cli/src/commands/start.ts
- packages/haul-core-legacy/src/compiler/worker/runWebpackCompiler.js
- packages/haul-core/src/server/Server.ts
- yarn.lock
For `haul bundle` command, there's a [restriction](https://github.com/callstack/haul/blob/22efe80fc7e0d4f50c046d5dd767a15c32428cf1/packages/haul-cli/src/commands/shared/prepareWebpackConfig.ts#L53) that webpack config must contain `index` or `main` entry. This restriction can be lifted for `haul multi-bundle` via [`--skip-host-check`](https://github.com/callstack/haul/blob/master/packages/haul-cli/src/commands/multiBundle.ts#L137) flag, but cannot be bypassed when running `haul start`.
This PR ports `--skip-host-check` flag to `haul start` so multi-bundle settings without `index` nor `main` entry can be served.
> fix: add `--skip-host-check` flag to `start` command

- packages/haul-cli/src/commands/start.ts
Earlier addition of `--skip-host-check` flag set its default value to a string `'false'` instead of boolean `false`, causing it to be incorrectly true-y by default.
> fix: default value type for --skip-host-check

- packages/haul-core/src/server/setupCompilerRoutes.ts
#729 breaks react-native-windows projects, as it omits platforms other than `ios` and `android`:
```
done ▶︎ Packager server running on http://localhost:8081
info ▶︎ Chrome Remote debugger connected
info ▶︎ GET /launch-js-devtools 200
info ▶︎ React Native debugger client connected
info ▶︎ Compiling bundle "index" for platform windows
error ▶︎ Debug: internal, implementation, error
TypeError: Cannot read property 'alreadySet' of undefined
at isUserChangedAlreadySetBundleOptions
(D:\playground\HaulRepro\node_modules\@haul-bundler\core\build\server\setupCompilerRoutes.js:191:23)
at handler (D:\playground\HaulRepro\node_modules\@haul-bundler\core\build\server\setupCompilerRoutes.js:93:38)
at module.exports.internals.Manager.execute (D:\playground\HaulRepro\node_modules\@hapi\hapi\lib\toolkit.j …
```
> fix: Support user-defined platforms when serving

- packages/haul-core/src/webpack/loaders/babelWorkerLoader/vendor/transform.ts
In our project we use a different loader setting for TypeScript files from what's recommended in the [Recipes](https://github.com/callstack/haul/blob/master/docs/Recipes.md#with-ts-compiler-tsc).
TS files are loaded by `ts-loader` **then** a `babelWorkerLoader` with metro preset:
```
// Ugly experimental code below
const babelLoaderRule = config.module!.rules[1];
const babelLoaderDef = (babelLoaderRule.use as webpack.RuleSetUseItem[])[0] as webpack.RuleSetLoader;
(babelLoaderDef.options! as any).presets = [[require.resolve('metro-react-native-babel-preset'), { disableImportExportTransform: false }]];
config.module!.rules.push({
test: /\.tsx?$/,
loader: 'ts-loader',
options: {
onlyCompileBundledFiles: true,
transpileOnly: env.bundleTarget !== 'file',
compilerOptions: {
declaration: false, …
```
> fix: Fix incorrect sourcemap overwrite during transform

- e2e/react_native_0_60x_ts/__tests__/bundleOptions.android.test.ts
- e2e/react_native_0_60x_ts/__tests__/bundleOptions.ios.test.ts
- e2e/utils/bundle.ts
- e2e/utils/createBuildTimeTestSuite.ts
- fixtures/react_native_with_haul_0_60x/package.json
- fixtures/react_native_with_haul_0_60x_ts/App.tsx
- packages/haul-core/src/server/setupCompilerRoutes.ts
There was an error with unspecified query params (minify or dev) and error was thrown after second request because for the first time bundle options were set but weren't checked. Second request and query params were checked against previously set options + default options. If option wasn't specified then its value was undefined and because we are using default options for check it always will fail.
Added e2e tests for unspecified options
> Fix bundle options query params

- packages/haul-cli/src/main.ts
Leverage `yargs` API to handle unknown arguments.
```bash
$ haul unknown
Commands:
haul.js init          Generates necessary configuration files
haul.js bundle        Builds the app bundle for packaging. Run with
`--platform` flag to specify the platform [ios|android].
haul.js ram-bundle    Create ram-bundle
haul.js reload        Sends reload request to all devices that enabled live
reload
haul.js start         Starts a new webpack server
haul.js multi-bundle  Create multiple bundles to be used in multi-bundle mode
Options:
-h, --help                Show help                                  [boolean]
--verbose                 Print all logs including debug messages.   [boolean]
--output-file <filename>  Log all messages to a file.                 [string]
--json                    When …
```
> chore(haul-cli): handle unknown args

- package.json
- packages/haul-core/src/server/setupDevtoolRoutes.ts
- packages/haul-core/src/utils/importModule.ts
- packages/haul-explore/src/index.ts
- yarn.lock
Solves [Module.createRequireFromPath() is deprecated](https://github.com/callstack/haul/issues/746)
Node 14 has made it to long term support, and it crashes when used with Haul. To fix this I've bumped `@types/node` to currtent, and added `Module.createRequire` with fallback to `Module.createRequireFromPath` where only `Module.createRequireFromPath` was used before.
In addition I fixed type errors that came with the `@types/node` update.
I'm not sure how best to test, I ran the jest tests locally, and failed 7 test suites, 10 tests, and 3 snapshots on the PR branch vs 10 test suites, 15 tests and 3 snapshots on master. Looks like createRequireFromPath and createRequire are equivalent api equivalent, apart from createRequire supporting URL input, so they should be swappable.
> Support node 14

- packages/haul-preset-0.59/src/defaultConfig.ts
- packages/haul-preset-0.60/src/defaultConfig.ts
When building RAM bundles, there are a couple issues which occur with the source map:
1. The source map contains the transformed source code output of Babel, instead of the original source code.
2. The original file paths in the source map are prefixed with `node_modules/@haul-bundler/core/build/webpack/loaders/babelWorkerLoader/index.js??ref--5-0!`.
Setting the webpack config to use `devtool: 'source-map'`, when building RAM bundles, appears to resolve these issues.
1. Build a RAM bundle of an RN app with Haul and produce a source map of the bundle. For reference I've included 
[source maps.zip](https://github.com/callstack/haul/files/6174504/source.maps.zip), which includes source maps from the default `react-native init` Android app, both with and without this fix.
2. Examine the …
> fix: provide original code in source maps when using RAM bundles
