callstack/haul

docs/CLI Commands.md

In the first paragraph, there is a tiny grammar problem.

Tiny Grammar Problem

---

src/server/middleware/devToolsMiddleware.js
src/server/middleware/liveReloadMiddleware.js
src/server/middleware/statusPageMiddleware.js

@satya164 had [discovered](https://github.com/callstack-io/haul/pull/74#discussion_r109288897) this, i just beat him to the PR.

Switches req.url to req.path.

---

README.md
flow-typed/npm/express_v4.x.x.js
package.json
src/logger.js
src/server/index.js
src/server/middleware/loggerMiddleware.js
src/server/middleware/rawBodyMiddleware.js
src/server/middleware/symbolicateMiddleware.js
src/server/middleware/systraceMiddleware.js
src/types.js

Also, implements `logger.debug` used by loggerMiddleware and systraceMiddleware so that the output stays consistent.

Adds systrace middleware and removes logger boilerplate

---

src/server/index.js
src/server/middleware/missingBundleMiddleware.js

Better error message

---

src/commands/init.js

fixed path to haul-integrate.sh script in init.js

---

src/commands/init.js
src/utils/isReactNativeProject.js

Issue #157 
This PR checks in `dev` and `peer` just in case someone had it set up differently.

Check in all places for react-native

---

.flowconfig
.gitignore
jest/helpers.js
package.json
src/__tests__/__snapshots__/cliEntry.test.js.snap
src/__tests__/__snapshots__/logger.test.js.snap
src/__tests__/cliEntry.test.js
src/__tests__/logger.test.js
src/cliEntry.js

**Summary**
After #200 is merged (which is current base of this PR – to be changed), I'd like to add some more tests. Here are tests for CLI entry.

Unit tests for CLI entry

---

src/utils/makeReactNativeConfig.js

Fix sourcemaps in dev

---

docs/Code Push.md

This doc describes how to use Haul with CodePush

CodePush integration docs

---

docs/hmr/Setup.md

Looking at adding HMR support, spotted this

Minor typo fix

---

src/__tests__/__snapshots__/cliEntry.test.js.snap
src/cliEntry.js
src/commands/reload.js
src/server/assets/debugger.html
src/server/middleware/liveReloadMiddleware.js

Small feature that allows to reload your App(s), by using `Reload` button at debugger. 
This uses Live Reload feature, so in order to make it work on Your device, make sure Live Reload is active.

Reload button

---

src/utils/getBabelConfig.js

Allow to find and merge .babelrc into default config

---

.flowconfig
jest/helpers.js
package.json
src/commands/bundle.js
src/commands/init.js
src/commands/reload.js
src/commands/start.js
src/hot/client/hotApi.js
src/hot/client/hotPatch.js
src/loaders/assetLoader.js
src/resolvers/AssetResolver.js
src/server/middleware/rawBodyMiddleware.js
src/types.js
src/utils/__tests__/__snapshots__/getBabelConfig.test.js.snap
src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
src/utils/exec.js
src/utils/haulPortHandler.js
yarn.lock

**Summary**
We had quite an outdated Flow, so this PR includes the latest.
Also because github failed to merge snapshots after #213 and #242, I had to re-record them, so this fixes CI btw.

 chore: bump flow to 0.57.2

---

.npmignore

**Summary**
Fixes #255.
**Test plan**
Tested with `yarn pack`, this is what should be published now:
```sh
├── CODE_OF_CONDUCT.md
├── LICENSE
├── README.md
├── bin
│   └── cli.js
├── hot
│   ├── index.js
│   └── patch.js
├── package.json
├── src
│   ├── cli.js
│   ├── cliEntry.js
│   ├── commands
│   │   ├── bundle.js
│   │   ├── init.js
│   │   ├── reload.js
│   │   └── start.js
│   ├── errors.js
│   ├── hot
│   │   ├── babelPlugin.js
│   │   └── client
│   │       ├── hotApi.js
│   │       ├── hotClient.js
│   │       ├── hotPatch.js
│   │       ├── importScriptsPolyfill.js
│   │       ├── index.js
│   │       └── utils.js
│   ├── loaders
│   │   └── assetLoader.js
│   ├── logger.js
│   ├── messages
│   │   ├── bundleBuilding.js
│   │   ├── bundleBuilt.js
│   │   ├── bundleFailed.js
│   …
```

fix: release only what's necessary to npm

---

src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
src/utils/makeReactNativeConfig.js

We removed it by a mistake, it's now back.

Revert exclude

---

src/commands/bundle.js
src/commands/start.js
src/messages/bundleFailed.js
src/server/index.js

feat(build): when build fails -> print an error with a stacktrace

---

src/commands/bundle.js
src/commands/start.js
src/messages/initialBundleInformation.js
src/messages/initialStartInformation.js
src/utils/__tests__/getEntryFiles.test.js
src/utils/__tests__/makeReactNativeConfig.test.js
src/utils/getEntryFiles.js
src/utils/makeReactNativeConfig.js

Now we handle different webpack entries, by injecting necessary polyfills to each entry.
Also applied changes to displaying proper entry files messages

Handle different webpack entries

---

src/hot/babelPlugin.js
src/hot/client/hotClient.js
src/server/middleware/hotMiddleware.js
src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
src/utils/makeReactNativeConfig.js

Update HMR's babel plugin to support new structure and fix multicompiler mode

---

src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
src/utils/makeReactNativeConfig.js

I've found that on iOS my bundle was about 15 MB because of all of the source-maps. With this fix, it dropped to 2.3 MB.

feat(bundle): better minification

---

.gitignore
fixtures/react-native-clean/.gitignore
fixtures/react-native-with-haul/.gitignore
src/commands/init.js

We're not using happypack anymore.

Remove happypack leftovers

---

docs/Recipes.md

Add a small recipe which explains how to integrate haul with detox

Add a recipe for running detox tests

---

bin/cli.js

Do not use foreign Babel configs

---

package.json
src/hot/client/hotPatch.js
src/hot/client/index.js
src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
src/utils/makeReactNativeConfig.js
src/utils/polyfillEnvironment.js
yarn.lock

Fix HMR error on Android (w/o debugger attached) + use valid URL

---

README.md

Not everyone uses yarn so I've added instructions for those people still on npm.

Add usage instructions for npm users

---

src/resolvers/AssetResolver.js
src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap

Fix issues when using with `vector-icons`:
```
./node_modules/@expo/vector-icons/fonts/FontAwesome.ttf
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
@ ./node_modules/@expo/vector-icons/FontAwesome.js 1:466-500
@ ./node_modules/@expo/vector-icons/index.js
@ ./node_modules/expo/src/Icon.js
@ ./node_modules/expo/src/Expo.js
@ ./node_modules/react-native-scripts/build/bin/crna-entry.js
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./node_modules/react-native-scripts/build/bin/crna-entry.js
```

Added more asset types

---

fixtures/README.md
fixtures/example-app/index.js

Update doc and remove old import

---

src/utils/makeReactNativeConfig.js
src/utils/polyfillEnvironment.js

Properly resolve dev server origin

---

src/loaders/assetLoader.js

Android assets

---

package.json
src/babelRegister.js
src/server/middleware/devToolsMiddleware.js
src/utils/__tests__/__snapshots__/getConfig.test.js.snap
src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
src/utils/makeReactNativeConfig.js
yarn.lock

Added support for pnpm and fixing debugging ui. 
https://github.com/callstack/haul/issues/432

pnpm support / fix debugging ui

---

docs/Configuring_Your_Project.md

docs: RCT_NO_LAUNCH_PACKAGER

---

.gitignore
docs/CLI Commands.md
fixtures/react-native-clean/ios/Test.xcodeproj/project.pbxproj
jest/helpers.js
package.json
src/cli.js
src/commands/bundle.js
src/loaders/assetLoader.js
src/resolvers/AssetResolver.js
src/utils/__tests__/__snapshots__/getConfig.test.js.snap
src/utils/__tests__/__snapshots__/makeReactNativeConfig.test.js.snap
src/utils/__tests__/getConfig.test.js
src/utils/findProvidesModule.js
src/utils/getBabelConfig.js
src/utils/makeReactNativeConfig.js
src/utils/resolveModule.js
yarn.lock

List of improvements:
- added progress indicator for bundle command
- added more log/trace messages that allow understanding of how the tool is executed
- hidden flag `--verbose` introduced, for making a possible run of the tool in the deep debug/verbose mode
- speed boost. caching and multi-core loaders added. (visually its a 20-50% improvement on large project)

Improvements

---

src/utils/makeReactNativeConfig.js

I will fix integration tests shortly.

bugfix: Can't release application with latest haul #487

---

src/__tests__/__snapshots__/cliEntry.test.js.snap
src/commands/start.js
src/constants.js

- This is useful for projects running haul within the context of
a Procfile

Ability to disable the prompt if the port is in use

---

src/resolvers/AssetResolver.js
src/resolvers/__tests__/resolvers.test.js

Resolving assets based on requested platform [RFC]

---

packages/haul-core/src/config/createPreset.ts
packages/haul-core/src/config/types.ts
packages/haul-core/src/index.ts

Resolves
https://github.com/callstack/haul/projects/2#card-21105878

[FIX] - support function in config

---

packages/haul-cli/src/commands/ramBundle.ts
packages/haul-core-legacy/src/commands/init.js
packages/haul-core/package.json
packages/haul-core/src/config/getRamBundleConfig.ts
packages/haul-core/src/config/types.ts
packages/haul-core/src/index.ts
packages/haul-ram-bundle-webpack-plugin/package.json
packages/haul-ram-bundle-webpack-plugin/src/WebpackRamBundlePlugin.ts
yarn.lock

Resolves https://github.com/callstack/haul/projects/2#card-21106023

[FEAT] minify modules (terser)

---

packages/haul-core/package.json
packages/haul-core/src/webpack/ReactNativeTarget.ts
packages/haul-core/src/webpack/plugins/ReactNativeEnvPlugin.ts
packages/haul-preset-0.59/src/defaultConfig.ts
yarn.lock

https://github.com/callstack/haul/projects/2#card-21106089

feat: dynamic imports support in static bundle

---

packages/haul-core-legacy/src/server/middleware/compilerMiddleware.js
packages/haul-core-legacy/src/server/util/createDeltaBundle.js

[FIX] - delta bundle

---

fixtures/exampleApp_0_59x/package.json
packages/haul-cli/src/commands/ramBundle.ts
packages/haul-core/src/config/types.ts
packages/haul-core/src/webpack/plugins/ReactNativeEnvPlugin.ts
packages/haul-ram-bundle-webpack-plugin/src/WebpackRamBundlePlugin.ts
packages/haul-ram-bundle-webpack-plugin/src/__tests__/integration.test.ts

https://github.com/callstack/haul/projects/2#card-21279812

feat: respect dev minify ram bundle

---

fixtures/exampleApp_0_59x/android/app/build.gradle
packages/haul-cli/src/commands/ramBundle.ts
packages/haul-ram-bundle-webpack-plugin/src/FileRamBundle.ts
packages/haul-ram-bundle-webpack-plugin/src/IndexRamBundle.ts
packages/haul-ram-bundle-webpack-plugin/src/WebpackRamBundlePlugin.ts
packages/haul-ram-bundle-webpack-plugin/src/__tests__/FileRamBundle.test.ts
packages/haul-ram-bundle-webpack-plugin/src/__tests__/IndexRamBundle.test.ts
packages/haul-ram-bundle-webpack-plugin/src/__tests__/integration.test.ts
packages/haul-ram-bundle-webpack-plugin/src/utils.ts

https://github.com/callstack/haul/projects/2#card-21105966

feat: add file ram bundle support

---

packages/haul-cli/package.json
packages/haul-cli/src/main.ts
yarn.lock

Support `--node-inspector` and `--haul-inspector` args

[FEAT] Add inspectors flags to command arguments

---

packages/haul-cli/src/commands/ramBundle.ts

Fix `--indexed-ram-budle` flag

fix indexed-ram-bundle flag

---

packages/haul-basic-bundle-webpack-plugin/src/WebpackBasicBundlePlugin.ts
packages/haul-core/assets/debugger.html
packages/haul-core/assets/debugger.js
packages/haul-core/assets/debuggerWorker.js
packages/haul-core/src/server/Server.ts
packages/haul-core/src/server/WebSocketDebuggerProxy.ts
packages/haul-core/src/server/setupDevtoolRoutes.ts
packages/haul-core/src/server/websocketProxy.ts
packages/haul-ram-bundle-webpack-plugin/runtime/bootstrap.js

Scaffolding for multi-bundle support in remote debugger.

feat: refactor debugger proxy and worker script

---

packages/haul-babel-preset-react-native/package.json
packages/haul-babel-preset-react-native/src/index.ts
packages/haul-babel-preset-react-native/src/transforms/__tests__/__snapshots__/stripDeadPlatformSelect.test.ts.snap
packages/haul-babel-preset-react-native/src/transforms/__tests__/stripDeadPlatformSelect.test.ts
packages/haul-babel-preset-react-native/src/transforms/stripDeadPlatformSelect.ts
packages/haul-basic-bundle-webpack-plugin/src/WebpackBasicBundlePlugin.ts
packages/haul-cli/src/commands/bundle.ts
packages/haul-cli/src/commands/multiBundle.ts
packages/haul-cli/src/commands/ramBundle.ts
packages/haul-core/assets/debuggerWorker.js
packages/haul-core/src/utils/sortBundlesByDependencies.ts

* Babel transform to strip unused `Platform.select` platform code when creating static bundle
* Remove unnecessary `__webpack_require__.p` from async chunk loading code
* Fix response from debugger worker when communicating through bridge

Optimisation babel transform + fixes

---

packages/haul-core-legacy/src/compiler/Compiler.js
packages/haul-core-legacy/src/compiler/worker/runWebpackCompiler.js
packages/haul-core/src/runtime/Logger.ts

fix: use proxy method instead of Proxy for logger in compiler fork (fixes #602)

---

docs/Recipes.md
packages/haul-core/assets/debugger.html
packages/haul-core/assets/debugger.js
packages/haul-core/assets/debuggerWorker.js
packages/haul-core/src/server/setupDevtoolRoutes.ts

feat: support vscdoe-react-native extension

---

packages/haul-cli/src/commands/start.ts
packages/haul-core/src/preset/makeConfigFactory.ts
packages/haul-core/src/server/UserInterface.ts

fix: --port option not being used (fixes #607)

---

docs/Recipes.md

https://github.com/callstack/haul/issues/629
I noticed that one couldn't use Typescript features like const enums with ts-loader, although the docs stated that it should work.
This commit expands the Typescript documentation, so that it includes a section about using the Typescript Compiler only without Babel.
N/A.

docs: improve Typescript documentation

---

packages/haul-cli/README.md

Made the license badge point to the respective file.
N/A

[Docs]: fix license link

---

packages/haul-preset-0.59/src/defaultConfig.ts
packages/haul-preset-0.60/src/defaultConfig.ts

fix: add aliasFields to webpack config

---

docs/Recipes.md

docs: update react-native-windows recipe

---

packages/haul-babel-preset-react-native/README.md
packages/haul-babel-preset-react-native/src/index.ts

feat: export functions for getting a list of plugins and utilities

---

packages/haul-preset-0.59/src/defaultConfig.ts
packages/haul-preset-0.60/src/defaultConfig.ts

fix: use correct aliasFileds to exclude Node polyfills from bundle

---

packages/haul-core/src/preset/__tests__/__snapshots__/makeConfigFactory.test.ts.snap
packages/haul-core/src/preset/makeConfigFactory.ts
packages/haul-core/src/preset/utils/getSourceMapPlugin.ts

fix: source map generated at incorrect path

---

packages/haul-core/src/config/types.ts
packages/haul-core/src/preset/__tests__/__snapshots__/makeConfigFactory.test.ts.snap
packages/haul-core/src/preset/makeConfigFactory.ts
packages/haul-core/src/preset/utils/getBundlePlugin.ts
packages/haul-ram-bundle-webpack-plugin/runtime/bootstrap.js
packages/haul-ram-bundle-webpack-plugin/src/WebpackRamBundlePlugin.ts
packages/haul-ram-bundle-webpack-plugin/src/__tests__/integration.test.ts

fix: use `bundleId` instead of `bundleName` for multibundle

---

fixtures/react_native_with_haul_0_60x/haul.config.js
fixtures/react_native_with_haul_0_60x/package.json
fixtures/react_native_with_haul_0_60x/yarn.lock
packages/haul-core/src/webpack/loaders/babelWorkerLoader/babelWorkerLoader.ts
packages/haul-core/src/webpack/loaders/babelWorkerLoader/index.ts
packages/haul-core/src/webpack/loaders/babelWorkerLoader/worker.ts

fix: use babel worker loader as non-pitch loader

---

e2e/react_native_0_60x_ts/__tests__/bundleOptions.android.test.ts
e2e/react_native_0_60x_ts/__tests__/bundleOptions.ios.test.ts
packages/haul-core/src/server/setupCompilerRoutes.ts

Added warn msg to terminal output when user changed bundle options
